apiVersion: apps/v1
kind: Deployment
metadata:
  name: char-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: char-frontend
  template:
    metadata:
      labels:
        app: char-frontend
    spec:
      containers:
      - name: frontend
        image: irshadahmed04/char-frontend:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: char-frontend
spec:
  selector:
    app: char-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  type: NodePort
